# don't use spring boot's property anymore!!

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com # replace with your own
spring:
  autoconfigure:
    exclude:
      # get rid of "Using default security password" logs and basic auth defaults
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

app:
  issuers:
    - https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/
    - https://<your-tenant>.b2clogin.com/<your-tenant>.onmicrosoft.com/<your-policy>/v2.0/
